export const variants = [
  {
    dir: "ai-saas-template",
    packageName: "@datbuilds/ai-saas-template",
    port: 3101,
    product: {
      code: "ai-saas-template",
      name: "PulsePilot AI",
      companyName: "DatBuilds",
      websiteUrl: "http://localhost:3101",
      legalEntity: "DatBuilds Pte. Ltd.",
      governingLaw: "Singapore",
      refundPolicy:
        "Refund requests are reviewed within 14 days for annual plans and 7 days for monthly plans when no material usage has occurred.",
      dataRetentionPolicy:
        "Workspace context, runs, billing, and support records are retained only as long as needed to operate automations, secure access, satisfy legal obligations, and resolve disputes.",
    },
    site: {
      description:
        "PulsePilot AI keeps AI workflows, operator approvals, billing, and account control in one focused control room.",
      corePurpose:
        "orchestrate AI workflows, approvals, and delivery operations in one focused control room",
      problemStatement:
        "AI operations often sprawl across prompts, automations, and disconnected handoffs. PulsePilot AI keeps execution, approvals, billing, and operator context in one calmer system.",
    },
    overview: {
      en: {
        heroTitle: "Operate AI workflows with fewer tabs, fewer handoffs, and tighter control.",
        heroDescription:
          "PulsePilot AI gives operators one clear layer to launch runs, review outcomes, trace failures, and move work forward without losing context.",
        primaryCta: "Open workspace",
        secondaryCta: "See workflow map",
      },
      de: {
        heroTitle: "Steuere AI-Workflows mit weniger Tabs, weniger Handoffs und mehr Kontrolle.",
        heroDescription:
          "PulsePilot AI gibt Teams eine klare Oberfläche, um Runs zu starten, Ergebnisse zu prüfen, Fehler nachzuvollziehen und Arbeit ohne Kontextverlust weiterzubewegen.",
        primaryCta: "Workspace öffnen",
        secondaryCta: "Workflow ansehen",
      },
    },
    howItWorks: {
      en: {
        eyebrow: "Workflow control",
        title: "From request intake to approved AI output in four tight steps.",
        description:
          "Built for AI operations teams that need visibility, approval paths, and reliable execution without rebuilding process every week.",
        signalChips: [
          { label: "Route", icon: "capture" },
          { label: "Review", icon: "detect" },
          { label: "Approve", icon: "impact" },
          { label: "Ship", icon: "action" },
        ],
        steps: [
          {
            step: "01",
            title: "Collect structured inputs",
            body: "Capture the request, source material, constraints, and owner before a run starts.",
            points: ["Request brief", "Context bundle", "Owner assignment"],
            icon: "capture",
            preview: {
              type: "form",
              title: "New AI request",
              label: "Workflow entry",
              value: "ops@company.com",
              status: "Context loaded",
              action: "Route",
            },
          },
          {
            step: "02",
            title: "Route work through the right model path",
            body: "Choose the right workflow, prompt frame, or model chain without exposing operators to raw setup noise.",
            points: ["Run type", "Model path", "Policy guardrails"],
            icon: "detect",
            preview: {
              type: "bars",
              title: "Routing confidence",
              metrics: [
                { label: "Policy review", value: "92%", fill: 92 },
                { label: "Prompt chain", value: "81%", fill: 81 },
                { label: "Escalation path", value: "64%", fill: 64 },
                { label: "Manual fallback", value: "36%", fill: 36 },
              ],
            },
          },
          {
            step: "03",
            title: "Review output before release",
            body: "Operators see what changed, what failed, and what still needs approval before the result goes live.",
            points: ["Diff review", "Risk flags", "Approval check"],
            icon: "impact",
            preview: {
              type: "table",
              title: "Review queue",
              rows: [
                { label: "Legal redline", value: "High risk" },
                { label: "Model hallucination", value: "Needs owner" },
                { label: "Missing source note", value: "Blocked" },
              ],
            },
          },
          {
            step: "04",
            title: "Ship and trace every outcome",
            body: "Publish the result, track downstream status, and keep a clean audit trail for later debugging.",
            points: ["Release action", "Outcome trace", "Run history"],
            icon: "action",
            preview: {
              type: "line",
              title: "Release outcome",
              beforeLabel: "Before 48m",
              afterLabel: "After 11m",
            },
          },
        ],
      },
      de: {
        eyebrow: "Workflow-Steuerung",
        title: "Von der Anfrage bis zum freigegebenen AI-Ergebnis in vier klaren Schritten.",
        description:
          "Für AI-Ops-Teams, die Sichtbarkeit, Freigaben und verlässliche Ausführung brauchen, ohne Prozesse ständig neu zu bauen.",
        signalChips: [
          { label: "Eingang", icon: "capture" },
          { label: "Prüfen", icon: "detect" },
          { label: "Freigeben", icon: "impact" },
          { label: "Ausliefern", icon: "action" },
        ],
        steps: [
          {
            step: "01",
            title: "Strukturierte Inputs sammeln",
            body: "Erfasse Anfrage, Material, Vorgaben und Verantwortliche, bevor ein Run startet.",
            points: ["Briefing", "Kontextpaket", "Owner"],
            icon: "capture",
            preview: {
              type: "form",
              title: "Neuer AI-Request",
              label: "Workflow-Eingang",
              value: "ops@company.com",
              status: "Kontext geladen",
              action: "Routen",
            },
          },
          {
            step: "02",
            title: "Über den richtigen Model-Pfad routen",
            body: "Wähle Workflow, Prompt-Rahmen oder Model-Kette, ohne Operators mit Setup-Lärm zu belasten.",
            points: ["Run-Typ", "Model-Pfad", "Guardrails"],
            icon: "detect",
            preview: {
              type: "bars",
              title: "Routing-Sicherheit",
              metrics: [
                { label: "Policy-Review", value: "92%", fill: 92 },
                { label: "Prompt-Kette", value: "81%", fill: 81 },
                { label: "Eskalationspfad", value: "64%", fill: 64 },
                { label: "Manueller Fallback", value: "36%", fill: 36 },
              ],
            },
          },
          {
            step: "03",
            title: "Output vor der Freigabe prüfen",
            body: "Teams sehen Änderungen, Fehler und fehlende Freigaben, bevor Ergebnisse live gehen.",
            points: ["Diff-Review", "Risiko-Hinweise", "Freigabe-Check"],
            icon: "impact",
            preview: {
              type: "table",
              title: "Review-Queue",
              rows: [
                { label: "Legal-Redline", value: "Hohes Risiko" },
                { label: "Model-Halluzination", value: "Owner nötig" },
                { label: "Quelle fehlt", value: "Blockiert" },
              ],
            },
          },
          {
            step: "04",
            title: "Ausliefern und Ergebnisse nachverfolgen",
            body: "Veröffentliche das Ergebnis, verfolge den Status und halte einen sauberen Audit-Trail bereit.",
            points: ["Release", "Outcome-Trace", "Run-Historie"],
            icon: "action",
            preview: {
              type: "line",
              title: "Release-Ergebnis",
              beforeLabel: "Vorher 48m",
              afterLabel: "Nachher 11m",
            },
          },
        ],
      },
    },
    pricingCopy: {
      en: {
        title: "Pricing for AI operations teams that need control, not seat sprawl.",
        description:
          "Three clean levels for piloting workflows, scaling approved runs, and running AI operations with governance.",
        monthlyLabel: "Monthly",
        yearlyLabel: "Yearly",
        yearlyDiscountLabel: "Save 18%",
        featuredLabel: "Most chosen",
      },
      de: {
        title: "Preise für AI-Ops-Teams, die Kontrolle statt Seat-Sprawl brauchen.",
        description:
          "Drei klare Levels für Pilotbetrieb, skalierte Freigaben und AI-Operations mit Governance.",
        monthlyLabel: "Monatlich",
        yearlyLabel: "Jährlich",
        yearlyDiscountLabel: "18% sparen",
        featuredLabel: "Am häufigsten gewählt",
      },
    },
    pricingPlans: [
      {
        code: "free",
        name: "Sandbox",
        description: "For testing one workflow lane and validating operator fit.",
        interval: "free",
        priceAmount: 0,
        currency: "USD",
        priceLabel: "$0",
        provider: "manual",
        providerVariantId: null,
        entitlements: ["core.workflow"],
        featured: false,
        active: true,
        sortOrder: 10,
        metadata: { source: "variant-seed", variant: "ai-saas" },
      },
      {
        code: "pro",
        name: "Operator",
        description: "For teams running approved workflows every week with standard review paths.",
        interval: "month",
        priceAmount: 3900,
        currency: "USD",
        priceLabel: "$39",
        provider: "lemon_squeezy",
        providerVariantId: "REPLACE_WITH_LEMON_SQUEEZY_VARIANT_OPERATOR",
        entitlements: ["core.workflow", "analytics.standard"],
        featured: true,
        active: true,
        sortOrder: 20,
        metadata: { variant_env: "LEMON_SQUEEZY_VARIANT_OPERATOR", source: "variant-seed", variant: "ai-saas" },
      },
      {
        code: "pro-yearly",
        name: "Control",
        description: "For multi-workflow AI operations that need governance, higher volume, and cleaner oversight.",
        interval: "year",
        priceAmount: 14900,
        currency: "USD",
        priceLabel: "$149",
        provider: "lemon_squeezy",
        providerVariantId: "REPLACE_WITH_LEMON_SQUEEZY_VARIANT_CONTROL",
        entitlements: ["core.workflow", "analytics.standard"],
        featured: false,
        active: true,
        sortOrder: 30,
        metadata: { variant_env: "LEMON_SQUEEZY_VARIANT_CONTROL", source: "variant-seed", variant: "ai-saas" },
      },
    ],
    auth: {
      brand: "PulsePilot AI",
      tagline: "Route. Review. Release.",
      titleHtml: "Operate AI<br />workflows, <em>clearly</em>",
      body:
        "The control room for AI requests, approvals, run history, and accountable delivery.",
      subtitle: "Sign in to continue to your AI operations workspace",
      cta: "Continue to workspace",
      features: [
        { title: "Run visibility", body: "Track every request, run, and approval from one surface.", tone: "violet" },
        { title: "Human checkpoints", body: "Review output before it moves into a live workflow.", tone: "blue" },
        { title: "Audit-ready history", body: "Keep a clean trail across prompts, actions, and outcomes.", tone: "green" },
      ],
    },
    messages: {
      common: { productName: "PulsePilot AI", companyName: "DatBuilds" },
      nav: { login: "Sign in" },
      pricing: {
        startPlan: "Choose {plan}",
        description:
          "Three clean levels for piloting workflows, scaling approved runs, and running AI operations with governance.",
        entitlements: {
          coreWorkflow: "Workflow orchestration",
          analyticsStandard: "Run analytics",
        },
      },
      auth: {
        pageLoginSubtitle: "Enter your work email and we will send you a magic link.",
        drawerLoginSubtitle: "Enter your email to access the AI operations workspace.",
      },
      faq: {
        title: "Help & FAQ",
        quickActions: {
          supportTitle: "Talk to support",
          supportBody: "Get help with runs, billing, or access issues.",
          pricingTitle: "Review plans",
          pricingBody: "Compare Sandbox, Operator, and Control.",
        },
        cards: {
          plans: "Plans & Capacity",
          billing: "Billing & Renewals",
          access: "Access & Roles",
          account: "Account Actions",
          privacy: "Data & Retention",
          support: "Troubleshooting",
        },
      },
      privacy: {
        heroTitleLead: "Privacy",
        heroTitleAccent: "Policy",
      },
      terms: {
        heroTitleLead: "Terms of",
        heroTitleAccent: "Service",
      },
      footer: { about: "PulsePilot AI keeps AI requests, approvals, and billing in one focused control room." },
    },
    footerLabel: "PulsePilot AI keeps AI requests, approvals, and billing in one focused control room.",
    css: {
      light: {
        bg: "#f4f7ff",
        surface: "rgba(255, 255, 255, 0.68)",
        surfaceSolid: "#ffffff",
        surfaceSoft: "#eef3ff",
        text: "#0d1726",
        textMuted: "#53627b",
        border: "rgba(84, 109, 164, 0.16)",
        primary: "#5668ff",
        primaryStrong: "#4658f2",
        shadow: "0 24px 80px rgba(82, 102, 180, 0.14)",
        headerBg: "rgba(255, 255, 255, 0.72)",
        panelBg: "rgba(255, 255, 255, 0.72)",
        inputBg: "#eef2ff",
        heroBg: "radial-gradient(circle at 12% 18%, rgba(121, 137, 255, 0.16), transparent 34%), radial-gradient(circle at 86% 14%, rgba(103, 195, 255, 0.14), transparent 28%), linear-gradient(180deg, #f7f9ff 0%, #f3f6ff 54%, #eff3ff 100%)",
      },
      dark: {
        bg: "#070a12",
        surface: "rgba(15, 18, 30, 0.72)",
        surfaceSolid: "#0a0f1c",
        surfaceSoft: "#11182c",
        text: "#edf3ff",
        textMuted: "#9aaccc",
        border: "rgba(129, 154, 230, 0.18)",
        primary: "#8fa2ff",
        primaryStrong: "#a8b8ff",
        shadow: "0 28px 90px rgba(0, 0, 0, 0.48)",
        headerBg: "rgba(10, 14, 24, 0.78)",
        panelBg: "rgba(14, 18, 30, 0.78)",
        inputBg: "#12192c",
        heroBg: "radial-gradient(circle at 12% 18%, rgba(117, 141, 255, 0.18), transparent 34%), radial-gradient(circle at 82% 12%, rgba(84, 188, 255, 0.12), transparent 30%), linear-gradient(180deg, #0a0d16 0%, #080b14 100%)",
      },
    },
  },
  {
    dir: "marketing-lite-template",
    packageName: "@datbuilds/marketing-lite-template",
    port: 3102,
    product: {
      code: "marketing-lite-template",
      name: "DriftKit Marketing",
      companyName: "DatBuilds",
      websiteUrl: "http://localhost:3102",
      legalEntity: "DatBuilds Ltd.",
      governingLaw: "England and Wales",
      refundPolicy:
        "Refund requests are reviewed within 14 days for annual plans and 5 days for monthly plans when campaign usage remains low.",
      dataRetentionPolicy:
        "Campaign records, billing events, workspace settings, and support history are retained only for service operation, reporting continuity, legal obligations, and dispute resolution.",
    },
    site: {
      description:
        "DriftKit Marketing keeps campaign planning, launch tracking, billing, and team access in one lightweight operating surface.",
      corePurpose:
        "plan, launch, and track campaigns in one lightweight operating surface",
      problemStatement:
        "Campaign work often fractures across docs, sheets, chats, and reporting tabs. DriftKit Marketing keeps planning, launch coordination, billing, and account controls in one calmer system.",
    },
    overview: {
      en: {
        heroTitle: "Launch campaigns with less noise and a cleaner line from plan to performance.",
        heroDescription:
          "DriftKit Marketing gives lean teams one bright workspace for campaign setup, channel handoff, pricing control, and post-launch clarity.",
        primaryCta: "Enter workspace",
        secondaryCta: "View launch flow",
      },
      de: {
        heroTitle: "Starte Kampagnen mit weniger Lärm und einem klaren Weg von Planung zu Performance.",
        heroDescription:
          "DriftKit Marketing gibt schlanken Teams einen klaren Workspace für Kampagnenaufbau, Channel-Handoff, Pricing und Auswertung.",
        primaryCta: "Workspace öffnen",
        secondaryCta: "Launch-Flow ansehen",
      },
    },
    howItWorks: {
      en: {
        eyebrow: "Campaign flow",
        title: "From campaign brief to shipped launch in four lightweight steps.",
        description:
          "Designed for lean marketing teams that need speed, visibility, and a lighter operational layer.",
        signalChips: [
          { label: "Brief", icon: "capture" },
          { label: "Align", icon: "detect" },
          { label: "Launch", icon: "impact" },
          { label: "Measure", icon: "action" },
        ],
        steps: [
          {
            step: "01",
            title: "Capture one campaign brief",
            body: "Keep audience, offer, channel mix, and timing in one source before work starts.",
            points: ["Audience", "Offer", "Channel plan"],
            icon: "capture",
            preview: {
              type: "form",
              title: "Campaign brief",
              label: "Primary campaign",
              value: "Q4 launch / paid-social",
              status: "Brief ready",
              action: "Launch",
            },
          },
          {
            step: "02",
            title: "Align creative and channel owners",
            body: "Bring execution owners into one timeline so launches do not drift across scattered notes.",
            points: ["Owner map", "Dependencies", "Ready status"],
            icon: "detect",
            preview: {
              type: "bars",
              title: "Launch readiness",
              metrics: [
                { label: "Creative complete", value: "88%", fill: 88 },
                { label: "Tracking setup", value: "74%", fill: 74 },
                { label: "Landing QA", value: "61%", fill: 61 },
                { label: "Channel approvals", value: "42%", fill: 42 },
              ],
            },
          },
          {
            step: "03",
            title: "Launch without guesswork",
            body: "Move from plan to release with cleaner visibility into what is approved, blocked, or still pending.",
            points: ["Launch board", "Approval pass", "Blockers"],
            icon: "impact",
            preview: {
              type: "table",
              title: "Go-live queue",
              rows: [
                { label: "Meta creative set", value: "Approved" },
                { label: "Email segment", value: "Pending" },
                { label: "LP hero update", value: "Blocked" },
              ],
            },
          },
          {
            step: "04",
            title: "Review outcome and next action",
            body: "See what shipped, what converted, and what the team should adjust next.",
            points: ["Outcome view", "Performance notes", "Next move"],
            icon: "action",
            preview: {
              type: "line",
              title: "Campaign lift",
              beforeLabel: "Before 1.8%",
              afterLabel: "After 3.6%",
            },
          },
        ],
      },
      de: {
        eyebrow: "Kampagnen-Flow",
        title: "Vom Briefing bis zum Launch in vier leichten Schritten.",
        description:
          "Für schlanke Marketing-Teams, die Tempo, Sichtbarkeit und einen leichteren Operations-Layer brauchen.",
        signalChips: [
          { label: "Briefing", icon: "capture" },
          { label: "Ausrichten", icon: "detect" },
          { label: "Launchen", icon: "impact" },
          { label: "Messen", icon: "action" },
        ],
        steps: [
          {
            step: "01",
            title: "Ein Kampagnen-Briefing erfassen",
            body: "Halte Zielgruppe, Angebot, Channel-Mix und Timing an einer Stelle fest.",
            points: ["Zielgruppe", "Angebot", "Channel-Plan"],
            icon: "capture",
            preview: {
              type: "form",
              title: "Kampagnen-Briefing",
              label: "Hauptkampagne",
              value: "Q4 Launch / Paid Social",
              status: "Briefing bereit",
              action: "Starten",
            },
          },
          {
            step: "02",
            title: "Creative- und Channel-Owner ausrichten",
            body: "Führe Verantwortliche in einer Timeline zusammen, damit Launches nicht in Notizen verloren gehen.",
            points: ["Owner-Map", "Abhängigkeiten", "Ready-Status"],
            icon: "detect",
            preview: {
              type: "bars",
              title: "Launch-Readiness",
              metrics: [
                { label: "Creative fertig", value: "88%", fill: 88 },
                { label: "Tracking-Setup", value: "74%", fill: 74 },
                { label: "Landing-QA", value: "61%", fill: 61 },
                { label: "Channel-Freigaben", value: "42%", fill: 42 },
              ],
            },
          },
          {
            step: "03",
            title: "Ohne Rätsel launchen",
            body: "Behalte im Blick, was freigegeben, blockiert oder noch offen ist.",
            points: ["Launch-Board", "Freigabe", "Blocker"],
            icon: "impact",
            preview: {
              type: "table",
              title: "Go-live Queue",
              rows: [
                { label: "Meta Creative Set", value: "Freigegeben" },
                { label: "E-Mail Segment", value: "Offen" },
                { label: "LP Hero Update", value: "Blockiert" },
              ],
            },
          },
          {
            step: "04",
            title: "Ergebnis und nächsten Schritt prüfen",
            body: "Sieh, was live ging, was konvertierte und was das Team als Nächstes anpassen sollte.",
            points: ["Ergebnis", "Performance-Notizen", "Nächster Schritt"],
            icon: "action",
            preview: {
              type: "line",
              title: "Kampagnen-Uplift",
              beforeLabel: "Vorher 1,8%",
              afterLabel: "Nachher 3,6%",
            },
          },
        ],
      },
    },
    pricingCopy: {
      en: {
        title: "Lightweight pricing for campaign teams that want velocity without bloat.",
        description:
          "Three levels for small launches, growing channel programs, and coordinated multi-campaign work.",
        monthlyLabel: "Monthly",
        yearlyLabel: "Yearly",
        yearlyDiscountLabel: "Save 15%",
        featuredLabel: "Popular",
      },
      de: {
        title: "Leichte Preise für Kampagnen-Teams, die Tempo ohne Ballast wollen.",
        description:
          "Drei Levels für kleine Launches, wachsende Channel-Programme und koordinierte Multi-Kampagnen-Arbeit.",
        monthlyLabel: "Monatlich",
        yearlyLabel: "Jährlich",
        yearlyDiscountLabel: "15% sparen",
        featuredLabel: "Beliebt",
      },
    },
    pricingPlans: [
      {
        code: "free",
        name: "Lite",
        description: "For testing one active campaign lane with a lean team.",
        interval: "free",
        priceAmount: 0,
        currency: "USD",
        priceLabel: "$0",
        provider: "manual",
        providerVariantId: null,
        entitlements: ["core.workflow"],
        featured: false,
        active: true,
        sortOrder: 10,
        metadata: { source: "variant-seed", variant: "marketing-lite" },
      },
      {
        code: "pro",
        name: "Growth",
        description: "For teams coordinating recurring campaigns and channel execution each month.",
        interval: "month",
        priceAmount: 2400,
        currency: "USD",
        priceLabel: "$24",
        provider: "lemon_squeezy",
        providerVariantId: "REPLACE_WITH_LEMON_SQUEEZY_VARIANT_GROWTH",
        entitlements: ["core.workflow", "analytics.standard"],
        featured: true,
        active: true,
        sortOrder: 20,
        metadata: { variant_env: "LEMON_SQUEEZY_VARIANT_GROWTH", source: "variant-seed", variant: "marketing-lite" },
      },
      {
        code: "pro-yearly",
        name: "Studio",
        description: "For multi-channel planning with faster approvals, clearer reporting, and lower annual cost.",
        interval: "year",
        priceAmount: 8900,
        currency: "USD",
        priceLabel: "$89",
        provider: "lemon_squeezy",
        providerVariantId: "REPLACE_WITH_LEMON_SQUEEZY_VARIANT_STUDIO",
        entitlements: ["core.workflow", "analytics.standard"],
        featured: false,
        active: true,
        sortOrder: 30,
        metadata: { variant_env: "LEMON_SQUEEZY_VARIANT_STUDIO", source: "variant-seed", variant: "marketing-lite" },
      },
    ],
    auth: {
      brand: "DriftKit",
      tagline: "Plan. Launch. Measure.",
      titleHtml: "Launch marketing<br />campaigns, <em>lighter</em>",
      body:
        "The calm workspace for campaign briefs, launch readiness, billing, and performance follow-through.",
      subtitle: "Sign in to continue to your campaign workspace",
      cta: "Continue to workspace",
      features: [
        { title: "Clear launch plan", body: "Keep campaign brief, ownership, and timeline in one surface.", tone: "violet" },
        { title: "Channel alignment", body: "Reduce drift between creative, ops, and reporting handoffs.", tone: "blue" },
        { title: "Performance follow-through", body: "Review results and next actions without opening another tool.", tone: "green" },
      ],
    },
    messages: {
      common: { productName: "DriftKit Marketing", companyName: "DatBuilds" },
      nav: { login: "Login" },
      pricing: {
        startPlan: "Start {plan}",
        description:
          "Three levels for small launches, growing channel programs, and coordinated multi-campaign work.",
        entitlements: {
          coreWorkflow: "Campaign workflow",
          analyticsStandard: "Performance analytics",
        },
      },
      auth: {
        pageLoginSubtitle: "Enter your work email and we will send you a magic link.",
        drawerLoginSubtitle: "Enter your email to return to the campaign workspace.",
      },
      faq: {
        title: "Help & FAQ",
        quickActions: {
          supportTitle: "Contact support",
          supportBody: "Get help with launch setup, billing, or access.",
          pricingTitle: "See pricing",
          pricingBody: "Compare Lite, Growth, and Studio.",
        },
        cards: {
          plans: "Plans & Usage",
          billing: "Billing & Refunds",
          access: "Login & Access",
          account: "Workspace Actions",
          privacy: "Data & Privacy",
          support: "Issue Recovery",
        },
      },
      footer: { about: "DriftKit Marketing keeps campaign planning, billing, and follow-through in one lightweight workspace." },
    },
    footerLabel: "DriftKit Marketing keeps campaign planning, billing, and follow-through in one lightweight workspace.",
    css: {
      light: {
        bg: "#f8fafc",
        surface: "rgba(255, 255, 255, 0.7)",
        surfaceSolid: "#ffffff",
        surfaceSoft: "#f4f7fb",
        text: "#111827",
        textMuted: "#5b6475",
        border: "rgba(17, 24, 39, 0.1)",
        primary: "#7a6cf6",
        primaryStrong: "#6657ea",
        shadow: "0 22px 70px rgba(122, 108, 246, 0.12)",
        headerBg: "rgba(255, 255, 255, 0.76)",
        panelBg: "rgba(255, 255, 255, 0.76)",
        inputBg: "#f2f5fb",
        heroBg: "radial-gradient(circle at 14% 16%, rgba(122, 108, 246, 0.12), transparent 30%), radial-gradient(circle at 82% 20%, rgba(255, 173, 94, 0.12), transparent 26%), linear-gradient(180deg, #fcfdff 0%, #f7f9fc 56%, #f4f7fb 100%)",
      },
      dark: {
        bg: "#0b0d12",
        surface: "rgba(19, 22, 31, 0.72)",
        surfaceSolid: "#0f131c",
        surfaceSoft: "#171c28",
        text: "#edf2fb",
        textMuted: "#9ea9ba",
        border: "rgba(148, 163, 184, 0.16)",
        primary: "#a296ff",
        primaryStrong: "#b6adff",
        shadow: "0 28px 90px rgba(0, 0, 0, 0.44)",
        headerBg: "rgba(15, 18, 26, 0.8)",
        panelBg: "rgba(18, 22, 31, 0.8)",
        inputBg: "#171c28",
        heroBg: "radial-gradient(circle at 14% 16%, rgba(122, 108, 246, 0.16), transparent 30%), radial-gradient(circle at 82% 18%, rgba(255, 173, 94, 0.08), transparent 28%), linear-gradient(180deg, #0d1017 0%, #0a0c12 100%)",
      },
    },
  },
];
